Adds `From<iXXX>`  implementations to quadratic / field extensions
arkworks-rs/algebra pull request #263
Opened 2021-04-16 21:13 UTC by huitseeker

Those delegate to the respective, existing `From<uXXX>` implementations for` XXX` in `[8, 16, 32, 64, 128]`

2021-04-16 21:19 UTC, ValarDragon commented
Should we add these `From<ixxx>` trait bounds to the field trait?

2021-04-16 22:00 UTC, huitseeker commented
@ValarDragon Good question. It breaks compatibility of the libraries out there which may implement an `ark-ff::Field` on their own custom structure. At any rate, and so that this trait bound is easier to do in the future, I've added a commit doing the harder part of deriving the `impl`as part of the prime field macros.

2021-04-16 22:55 UTC, ValarDragon approved these changes
This looks good to me!
I've never seen / used paste before, but from looking at the docs this seems right to me.

cref #226, but I think its fine to assume that the ordering `(-p/2)...(p/2 - 1)` would be implied for signed ints here

2021-04-17 00:02 UTC, huitseeker commented
@ValarDragon FYI, you can inspect the output with [cargo expand](https://github.com/dtolnay/cargo-expand)
Here's the output of :
`cargo expand 2>/dev/null | grep -A7 -Ee 'impl<P:.*> From<[iu][0-9]+> for' |head -n 50`
https://gist.github.com/8f66c293bc5b231932dca3544460feec

2021-04-22 01:35 UTC, Pratyush requested changes

2021-04-22 23:17 UTC, Pratyush approved these changes

2021-04-22 23:17 UTC, merged