Documentation for the ff crate
arkworks-rs/algebra pull request #334
Opened 2021-10-20 23:03 UTC by mmagician

## Description

Related to: #314 

---

- [x] Targeted PR against correct branch (master)
- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Wrote unit tests
- [x] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

2021-11-09 02:51 UTC, Pratyush commented on ff/README.md
> +<h1 align="center">ark-ec</h1>
```suggestion
<h1 align="center">ark-ff</h1>
```

2021-11-09 19:38 UTC, Pratyush requested changes

2021-11-20 15:35 UTC, mmagician commented
I marked as ready for review. While not all public items are documented yet in the crate, I guess we can start here and add missing ones in the future?

2021-12-22 11:08 UTC, mmagician commented
@Pratyush Can we go ahead with merging in its current state already?

2021-12-22 12:18 UTC, Pratyush approved these changes

2021-12-22 13:01 UTC, merged