Update `QuadExtField::sqrt` for better performance
arkworks-rs/algebra pull request #352
Opened 2021-11-24 03:48 UTC by vlopes11

## Description

Currently, the QuadExtField uses an expensive runtime inverse of two
calculation defined as `P::BaseField::one().double().inverse()`.

With the proposed change, we compute the BigInt `(p+1)/2` that is ~15%
cheaper than the previous method.

Alternatively, we could require a compile-time constant provided by the
user that represents `1/2`. However, having a constant requirement to
satisfy a single use-case isn't ideal.

closes: #210

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (master)
- [x] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Updated relevant documentation in the code
- [x] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the GitHub PR explorer

- [ ] Wrote unit tests (tests are already covering this section such as `bls12_381::tests::test_fq2`)

2021-11-24 07:38 UTC, mmagician commented on ff/src/fields/models/quadratic_extension.rs
> +        let mut two_inv = <<P as QuadExtParameters>::BasePrimeField as PrimeField>::Params::MODULUS;
```suggestion
        let mut two_inv = <P::BasePrimeField as PrimeField>::Params::MODULUS;
```

2021-11-24 07:41 UTC, mmagician requested changes
Cool! I believe you can skip `<P as QuadExtsParameters>` since it's already dictated by the trait bounds.

2021-11-24 09:15 UTC, Pratyush approved these changes

2021-11-24 10:51 UTC, mmagician commented on ff/src/fields/models/quadratic_extension.rs
> +    P::BaseField: From<<<P as QuadExtParameters>::BasePrimeField as PrimeField>::BigInt>,
```suggestion
    P::BaseField: From<<P::BasePrimeField as PrimeField>::BigInt>,
```

2021-11-24 10:51 UTC, mmagician commented on ff/src/fields/models/quadratic_extension.rs
> +    P::BaseField: From<<<P as QuadExtParameters>::BasePrimeField as PrimeField>::BigInt>,
same here

2021-11-24 13:04 UTC, mmagician approved these changes

2021-11-24 13:23 UTC, daira approved these changes
Untested ACK.

2021-11-25 13:59 UTC, vlopes11 commented
Better rebase on top of https://github.com/arkworks-rs/algebra/pull/354 before merging so the performance difference will be clear and documented

2021-11-25 21:52 UTC, merged