Fix MontFp issue in fields with 64 * k bits
arkworks-rs/algebra pull request #550
Opened 2022-12-18 22:14 UTC by weikengchen

## Description

Previously, we changed the logic of field multiplication to support 64 * k bits, as in #532. 

We did not, however, change the one that affects the `MontFp` macro. This was previously not detected because `MontFp` uses a special, dedicated function to perform the computation (since it cannot use Fp because Fp has not yet been constructed), while the rest is using other functions.

This PR fixes so, in that `MontFp` will also call a function that is aware of the 64 * k issue.

This PR will also add more randomized tests.

closes: #549 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (master)
- [x] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer

TODO:
- [ ] Wrote unit tests

N/A:
- [ ] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`

2022-12-18 22:36 UTC, weikengchen commented
Randomized tests appear to be difficult to add, as several functions are private (and are intended to be so).

2022-12-19 09:23 UTC, mmagician commented
How about we add regression tests for the specific failure case that we know of? I think it's better to have a few tests not following our test-templates than not having them and risking incorrect computation now & in the future.

2022-12-20 01:34 UTC, weikengchen commented
Let me add one.

2022-12-20 09:24 UTC, Pratyush requested changes

2022-12-21 04:21 UTC, weikengchen commented
Update and cc @Pratyush 

- spare bit is now used
- added a test

2022-12-21 04:43 UTC, Pratyush approved these changes

2022-12-21 06:13 UTC, merged